project :: (#21) login&signup UI 만들기
team-nk/kim-il-jeong-ios pull request #24
Opened 2022-10-04 08:21 UTC by juyeong525

## 개요
> login&signup UI 만들기

## 작업사항
- login&signup UI 만들기

## 변경로직
- login&signup UI 만들기

2022-10-04 08:23 UTC, HongSJae approved these changes
^^

2022-10-04 10:17 UTC, kimdaehee0824 commented on iOS/Sources/Scene/Login&SignUp/UI/LoginVC.swift
> +    }
저거 줄바꿈이 이상해요

2022-10-04 10:45 UTC, juyeong525 commented on iOS/Sources/Scene/Login&SignUp/UI/LoginVC.swift
> +    }
형이 하셨는데,..

2022-10-04 14:04 UTC, kimdaehee0824 approved these changes

2022-10-05 02:03 UTC, kimdaehee0824 requested changes

2022-10-05 02:03 UTC, kimdaehee0824 commented on iOS/Sources/App/SceneDelegate.swift
> +        window?.rootViewController = naviMainViewController
내가 이거 BaseNC 만들어 놓은거 있거든
그거 https://github.com/YeongjoonAndIdol/NextStep-iOS/blob/main/iOS/Sources/Base/BaseNC.swift
이거를 복붙해서 저거를 바꾸자
그러면 Backbutton 없에는 코드를 굳이 안써도 됨

2022-10-05 02:06 UTC, kimdaehee0824 commented on iOS/Sources/App/SceneDelegate.swift
> +        window?.rootViewController = naviMainViewController
``` swift
import UIKit

class BaseNC: UINavigationController {

    private var backButtonImage: UIImage? {
        return NextStapAsset.Assets.backImage.image
            .withAlignmentRectInsets(UIEdgeInsets(top: 0.0, left: -12.0, bottom: 0.0, right: 0.0))
    }

    private var backButtonAppearance: UIBarButtonItemAppearance {
        let backButtonAppearance = UIBarButtonItemAppearance()
        backButtonAppearance.normal.titleTextAttributes = [.foregroundColor: UIColor.clear]
        return backButtonAppearance
    }

    static func makeNavigationController(rootViewController: UIViewController) -> BaseNC {
        let navigationController = BaseNC(rootViewController: rootViewController)
        navigationController.modalPresentationStyle = .fullScreen
        return navigationController
    }

    override func viewDidLoad() {
        super.viewDidLoad()
        setNavigationBarAppearance()
    }

    func setNavigationBarAppearance() {
        let appearance = UINavigationBarAppearance()
        let appearance2 = UINavigationBarAppearance()
        navigationBar.tintColor = NextStapAsset.Color.onBackGroundColor.color
        appearance.setBackIndicatorImage(backButtonImage, transitionMaskImage: backButtonImage)
        appearance2.setBackIndicatorImage(backButtonImage, transitionMaskImage: backButtonImage)

        appearance.configureWithTransparentBackground()
        appearance2.configureWithDefaultBackground()
        appearance.backButtonAppearance = backButtonAppearance
        appearance2.backButtonAppearance = backButtonAppearance
        navigationBar.standardAppearance = appearance2
        navigationController?.setNeedsStatusBarAppearanceUpdate()
        navigationBar.scrollEdgeAppearance = appearance
    }

}
```
이거 넣으면 될고야

2022-10-05 02:40 UTC, DSMInhyeKang approved these changes
ㅎㅎ

2022-10-05 02:51 UTC, kimdaehee0824 approved these changes

2022-10-05 02:53 UTC, merged