feat :: TabBarVC 구현
team-nk/kim-il-jeong-ios pull request #32
Opened 2022-10-19 23:31 UTC by DSMInhyeKang

## 개요
> 탭바 기능 구현

## 작업사항
- TabBarVC 구현

## 변경로직
- 

## UI

2022-10-20 00:57 UTC, kimdaehee0824 requested changes

2022-10-20 00:57 UTC, kimdaehee0824 commented on iOS/Sources/Base/TabBarVC.swift
> +//        )
주석 지워주세요

2022-10-20 00:57 UTC, kimdaehee0824 commented on iOS/Sources/App/SceneDelegate.swift
> +>>>>>>> Stashed changes
컨픽트 난거 자랑하세요?

2022-10-20 00:57 UTC, kimdaehee0824 commented on iOS/Sources/App/SceneDelegate.swift
> +>>>>>>> Stashed changes
아니 저게 뭔지 구글에 찾아보셨으면 좋겠는데

2022-10-20 00:57 UTC, kimdaehee0824 commented on iOS/Sources/App/SceneDelegate.swift
> +>>>>>>> Stashed changes
빌드 안되잖아요
확인 안하세요?

2022-10-20 00:57 UTC, kimdaehee0824 commented on iOS/Sources/Base/TabBarVC.swift
> +        ]
주석 지워주세요

2022-10-21 00:55 UTC, kimdaehee0824 approved these changes

2022-10-21 02:20 UTC, juyeong525 approved these changes

2022-10-21 02:26 UTC, HongSJae approved these changes
MainVC랑 연결 안해주셨네요 ㅠ 내가해야지

2022-10-21 03:57 UTC, merged